[package]
name = "mfsr"
version = "0.1.0"
edition = "2021"
authors = ["Matheus Filipe dos Santos Reinert"]


[dependencies]
ctrlc = "3.4.1"
fuser = "0.14.0"
libc = "0.2.149"
serde = {version="1.0.190", features = ["derive"]}
